/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/macbook.glb 
Author: Bastien Genbrugge (https://sketchfab.com/bastienBGR)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mini-macbook-pro-2b054523279747c8b5b2e5ed9ea7b311
Title: Mini MacBook Pro
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/macbook.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-8.578, -13.853, -133.996]} rotation={[Math.PI, -0.281, Math.PI]}>
        <mesh geometry={nodes.Muis_1_Mat_2.geometry} material={materials.material} />
        <mesh geometry={nodes.Muis_1_Mat_0.geometry} material={materials.Mat_0} />
      </group>
      <mesh geometry={nodes.MacBook_1_MacBook1_0.geometry} material={materials['MacBook.1']} position={[8.578, 13.853, 133.996]} rotation={[0, Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/macbook.glb')
